// Generated by https://quicktype.io

class Estate {
  int estateId;
  String estateName;
  String city;
  String country;
  String address;

  Estate({
    this.estateId,
    this.estateName,
    this.city,
    this.country,
    this.address,
  });

  factory Estate.fromJson(Map<String, dynamic> json) {
    return Estate(
      estateId: json['id'],
      estateName: json['estate_name'],
      city: json['city'],
      country: json['country'],
      address: json['address'] ?? '',
    );
  }
}



class HomeModel{
int id,userId,estateId;
String houseBlock;
Estate estate;

HomeModel({this.id,this.userId,this.estateId,this.houseBlock,this.estate});

factory HomeModel.fromJson(dynamic json){
  return HomeModel(

    id: json['id']??null,
    userId: json['user_id']??null,
    estateId: json['estate_id']??null,
    houseBlock: json['house_block']??null,
    estate: Estate.fromJson(json['estate'])

  );
}

}