// Generated by https://quicktype.io

class GatemanResidentRequest {
  int id;
  String name;
  dynamic username;
  String phone;
  String email;
  String image;
  String userType;
  String deviceId;
  String createdAt;
  String updatedAt;
  int requestId;
  int gatemanId;

  GatemanResidentRequest({
    this.id,
    this.name,
    this.username,
    this.phone,
    this.email,
    this.image,
    this.userType,
    this.deviceId,
    this.createdAt,
    this.updatedAt,
    this.requestId,
    this.gatemanId,
  });

  factory GatemanResidentRequest.fromJson(Map<String, dynamic> json){
    return GatemanResidentRequest(
      id: json['id'],
      phone: json['phone'],
      createdAt: json['created_at'],
      deviceId: json['device_id'],
      email: json['email'],
      gatemanId: json['gateman_id'],
      image: json['image'],
      name: json['name'],
      requestId: json['request_id'],
      updatedAt: json['updated_at'],
      username: json['username'],
      userType: json['user_type'],
    );
  }
}
