// Generated by https://quicktype.io

class Payment {
  int id;
  int userId;
  int homeId;
  int amount;
  String createdAt;
  String updatedAt;
  HomePayment home;
  UserPayment user;

  Payment({
    this.id,
    this.userId,
    this.homeId,
    this.amount,
    this.createdAt,
    this.updatedAt,
    this.home,
    this.user,
  });

  factory Payment.fromJson(Map<String, dynamic> json) {
    return Payment(
      id: json['id'],
      userId: json['user_id'],
      homeId: json['home_id'],
      amount: json['amount'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
      home: HomePayment.fromJson(json['home']),
      user: UserPayment.fromJson(json['home']),
    );
  }
}

class HomePayment {
  int id;
  int userId;
  int estateId;
  int houseNo;
  dynamic qrCode;
  String createdAt;
  String updatedAt;
  EstatePayment estate;

  HomePayment({
    this.id,
    this.userId,
    this.estateId,
    this.houseNo,
    this.qrCode,
    this.createdAt,
    this.updatedAt,
    this.estate,
  });

  factory HomePayment.fromJson(Map<String, dynamic> json) {
    return HomePayment(
      id: json['id'],
      userId: json['user_id'],
      estateId: json['estate_id'],
      houseNo: json['house_no'],
      qrCode: json['qr_code'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
      estate: EstatePayment.fromJson(json['home']),
    );
  }
}

class EstatePayment {
  int id;
  String estateName;
  String city;
  String country;
  String createdAt;
  String updatedAt;

  EstatePayment({
    this.id,
    this.estateName,
    this.city,
    this.country,
    this.createdAt,
    this.updatedAt,
  });

  factory EstatePayment.fromJson(Map<String, dynamic> json) {
    return EstatePayment(
      id: json['id'],
      estateName: json['estate_name'],
      city: json['city'],
      country: json['country'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
    );
  }
}

class UserPayment {
  int id;
  String firstName;
  String lastName;
  String email;
  String phone;
  String image;
  String createdAt;
  String updatedAt;

  UserPayment({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.phone,
    this.image,
    this.createdAt,
    this.updatedAt,
  });

  factory UserPayment.fromJson(Map<String, dynamic> json) {
    return UserPayment(
      id: json['id'],
      firstName: json['first_name'],
      lastName: json['last_name'],
      email: json['email'],
      phone: json['phone'],
      image: json['image'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
    );
  }
}
