// Generated by https://quicktype.io

class ServiceProvider {
  int id;
  String name;
  String phone;
  String description;
  String image;
  int estateId;
  String createdAt;
  String updatedAt;

  ServiceProvider({
    this.id,
    this.name,
    this.phone,
    this.description,
    this.image,
    this.estateId,
    this.createdAt,
    this.updatedAt,
  });

  factory ServiceProvider.fromJson(Map<String, dynamic> json) {
    return ServiceProvider(
      id: json['id'],
      name: json['name'],
      phone: json['phone'],
      description: json['description'],
      image: json['image'],
      createdAt: json['created_at'],
      estateId: json['estate_id'],
      updatedAt: json['updated_at'],
    );
  }
}

class ServiceProviderCategory {
  int id;
  String title;
  String createdAt;
  String updatedAt;

  ServiceProviderCategory({
    this.id,
    this.title,
    this.createdAt,
    this.updatedAt,
  });

  factory ServiceProviderCategory.fromJson(Map<String, dynamic> json) {
    return ServiceProviderCategory(
      id: json['id'],
      title: json['title'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
    );
  }
}
