// Generated by https://quicktype.io

class Visitor {
  int id;
  String name;
  String arrivalDate;
  String carPlateNo;
  String purpose;
  String image;
  String status;
  String timeIn;
  String timeOut;
  int userId;
  int homeId;

  Visitor({
    this.id,
    this.name,
    this.arrivalDate,
    this.carPlateNo,
    this.purpose,
    this.image,
    this.status,
    this.timeIn,
    this.timeOut,
    this.userId,
    this.homeId,
  });

  factory Visitor.fromJson(Map<String, dynamic> json) {
    return Visitor(
      id: json['id'],
      arrivalDate: json['arrival_date'],
      carPlateNo: json['car_plate_no'],
      homeId: json['home_id'],
      image: json['image'],
      name: json['name'],
      purpose: json['purpose'],
      status: json['status'],
      timeIn: json['time_in'] ?? '',
      timeOut: json['time_out'] ?? '',
      userId: json['user_id'],
    );
  }
}
