enum ErrorType {
  generic,
  timeout,
  network,
  invalid_credentials,
  token,
  email_taken,
  password_dont_match,
  phone,
  account_already_verified,
  verify_code_not_found,
  account_not_confimrmed,
  email_not_found,
  verify_code_atleast_5_chars,
  no_visitors_found,
  username_at_least_2_char,
  no_gateman_found,
  invalid_input_in_register
  unauthorized,
  no_requests_available,
  request_already_sent_to_gateman
}
